authors:
  apotgieter:
    name: Adam Potgieter
    description: Presenter & Writer
    avatar: https://github.com/Adampottie2hotmail/Self_Hosted_Freedom/blob/main/assets/avatars/apo.png?raw=true
    url: https://aroic-studios.co.uk
  alexvoss:
    name: Alex Voss
    description: Solutions Architect
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
  katharinalisalin:
    name: Kathi
    description: Communications
    avatar: https://avatars.githubusercontent.com/u/105352741
    url: https://github.com/katharinalisalin
